### ISSUE TITLE
`admin_init` is an action hook

### ISSUE THREAD

**Issue by benoitchantre** [WebDevStudios/WDS-Required-Plugins#26]
https://github.com/WebDevStudios/WDS-Required-Plugins/blob/c0976c2beadc81c116d78bd3bccc4dcfca2c6e6a/wds-required-plugins.php#L118-L119

`add_action` should be used instead of `add_filter`

**Comment by benoitchantre** [comment]
Fixed by #25.

**Comment by aubreypwd** [comment]
Thanks for your contribution!
