### ISSUE TITLE
Cannot switch site to multi-site.

### ISSUE THREAD

**Issue by JayWood** [WebDevStudios/WDS-Required-Plugins#6]
When using the plugin, if you're upgrading from a regular site to multi-site, you must clear the filtered array before you can continue.  Not a huge issue, but an issue nonetheless.

![image](https://cloud.githubusercontent.com/assets/2303074/7638329/f3f0bd18-fa41-11e4-8908-418c9ecccc59.png)

**Comment by JPry** [comment]
@JayWood You can use [this Gist](https://gist.github.com/JPry/8026015), and just add the other filters to the list:

```php
add_filter( 'wds_required_plugins', '__return_empty_array', 99 );
add_filter( 'wds_network_required_plugins', '__return_empty_array', 99 );
```
