### ISSUE TITLE
Block update checks

### ISSUE THREAD

**Issue by JPry** [WebDevStudios/WDS-Required-Plugins#7]
With some required plugins, there's a chance that an update will come along, or perhaps a plugin by the same name will be in the official WordPress.org repo. It would be nice to have the ability to either disable update checks entirely, or perhaps just disable the actual update process for plugins that are Required using this plugin.

Sample code from Mark Jaquith: https://markjaquith.wordpress.com/2009/12/14/excluding-your-plugin-or-theme-from-update-checks/

**Comment by tnorthcutt** [comment]
Would that possibly be better done in the plugin itself? E.g. if you have a plugin that you don't want to get updated, why not drop that code into the plugin?

**Comment by JPry** [comment]
> Would that possibly be better done in the plugin itself? E.g. if you have a plugin that you don't want to get updated, why not drop that code into the plugin?

If you're including a 3rd-party plugin, or even a plugin that is managed elsewhere, you may not have that option.

**Comment by JayWood** [comment]
@JPry Actually discussed this awhile back with some peeps at Maintainn, and it was decided that we didn't want to do this in the plugin, so.. in light of that, I did this:

https://github.com/JayWood/is-version-control
